# Generated by Django 4.0.2 on 2022-02-19 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
