# Generated by Django 4.0.2 on 2022-02-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_first_name_myuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
